PROPOSAL=proposal

all:
	pdflatex -file-line-error -interaction=nonstopmode $(PROPOSAL)

propsal:
	pdflatex -file-line-error -interaction=nonstopmode $(PROPOSAL)

clean:
	rm -f $(PROPOSAL).log $(PROPOSAL).aux $(PROPOSAL).synctex.gz

show:
	open $(PROPOSAL).pdf
